apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: frontend
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "frontend.haluk.haluk.com"        # Cloudflare da yahut benzeri yerlerde DNS kayıtlarının olması gerek
#    secretName: wildcard-haluk         # SSL kullanmayacaksan gerek yok.
  rules:
    - host: "frontend.haluk.haluk.com"  # Cloudflare da yahut benzeri yerlerde DNS kayıtlarının olması gerek
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000