trigger:
  branches:
    include:
      - main

pool:
  name: 'aws-build-agent-1' # Biz externalda konumlandırdığımız EC2 lar (ubuntu machine) üzerine build agent lar kurup bu işlemleri burdan yürütüyoruz.

variables: # Bu variable ları AzureDevops Library'den de çektirebilirdik.Ben pipe'ın içinde tanımnladım.
  DOCKER_REGISTRY: "docker.io"
  DOCKER_NAMESPACE: "halyil"
  BACKEND_IMAGE: "backend-app"
  FRONTEND_IMAGE: "frontend-app"
  IMAGE_VERSION: "v1.0"

stages:
- stage: Build_And_Push
  jobs:
  - job: Build_Backend
    displayName: "Build & Push Backend"
    steps:
    - task: Docker@2
      displayName: "Login to Docker Hub"
      inputs:
        command: login
        containerRegistry: $(DOCKER_REGISTRY)

    - task: Docker@2
      displayName: "Build Backend Image"
      inputs:
        command: build
        Dockerfile: backend/Dockerfile
        buildContext: backend
        repository: $(DOCKER_NAMESPACE)/$(BACKEND_IMAGE)
        tags: latest

    - script: |
        docker tag $(DOCKER_NAMESPACE)/$(BACKEND_IMAGE):latest $(DOCKER_NAMESPACE)/$(BACKEND_IMAGE):$(IMAGE_VERSION)
      displayName: "Tag Backend Image"

    - task: Docker@2
      displayName: "Push Backend Image"
      inputs:
        command: push
        repository: $(DOCKER_NAMESPACE)/$(BACKEND_IMAGE)
        tags: |
          latest
          $(IMAGE_VERSION)

  - job: Build_Frontend
    displayName: "Build & Push Frontend"
    steps:
    - task: Docker@2
      displayName: "Login to Docker Hub"
      inputs:
        command: login
        containerRegistry: $(DOCKER_REGISTRY)

    - task: Docker@2
      displayName: "Build Frontend Image"
      inputs:
        command: build
        Dockerfile: frontend/Dockerfile
        buildContext: frontend
        repository: $(DOCKER_NAMESPACE)/$(FRONTEND_IMAGE)
        tags: latest

    - script: |
        docker tag $(DOCKER_NAMESPACE)/$(FRONTEND_IMAGE):latest $(DOCKER_NAMESPACE)/$(FRONTEND_IMAGE):$(IMAGE_VERSION)
      displayName: "Tag Frontend Image"

    - task: Docker@2
      displayName: "Push Frontend Image"
      inputs:
        command: push
        repository: $(DOCKER_NAMESPACE)/$(FRONTEND_IMAGE)
        tags: |
          latest
          $(IMAGE_VERSION)
