apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: halyil/backend-app:v1.0
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://halukuser:'Ale3duysunkr@lSa3sun'@postgres:5432/halukyilmaz55"
